//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_book
    {
        public int author_id { get; set; }
        public int book_id { get; set; }
        public int author_book_id { get; set; }
    
        public virtual author_table author_table { get; set; }
        public virtual book_table book_table { get; set; }
    }
}
