//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book_table()
        {
            this.author_book = new HashSet<author_book>();
        }
    
        public int book_id { get; set; }
        public int author_id { get; set; }
        public string book_title { get; set; }
        public int book_price { get; set; }
        public string book_genre { get; set; }
        public int bookstore_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<author_book> author_book { get; set; }
        public virtual bookstore_table bookstore_table { get; set; }
    }
}
